#!/bin/zsh -e

reset='\e[0m'
red='\e[31m'
green='\e[32m'
yellow='\e[33m'
blue='\e[34m'
magenta='\e[35m'
cyan='\e[36m'

_COLOR=$1
_TEXT=${*:2}

case $_COLOR in
	"blue" | "red" | "green" | "yellow" | "magenta" | "cyan" | "aqua" )
		printf '%b\n' ${(P)_COLOR}$_TEXT$reset
		;;
	*)
		if [[ $_TEXT == '' ]]; then
			echo $_COLOR
		else
			echo $_TEXT
		fi
		;;
esac