#!/bin/zsh

# Include tools as binary functions
PATH=$PATH:$DOTFILES_PATH/tools

# Trap ctrl+c (abort script)
# To make sure that stty is restored
_STTY_STATE=$(stty -g)
reset_stty() {
	stty $_STTY_STATE &>/dev/null
}

TRAPINT() {
	reset_stty
	return 1
}

# Input arguments
_RESULT_FILE=$1

# Check if any output file has been provided
if [ -z $_RESULT_FILE ]; then
	color-print red "No output file provided"
	exit 1
fi

touch $_RESULT_FILE

shift
_OPTIONS=(${@})
_OPTIONS_LENGTH=$(expr ${#_OPTIONS[@]} - 1)
_CURSOR=0

# Check if any options has been provided
if [ "$_OPTIONS_LENGTH" -lt 0 ]; then
	color-print red "No options provided"
	exit 1
fi

clear_options() {
	tput civis
	tput cuu1
	tput el
	for _ in ${_OPTIONS[@]}; do
		tput cuu1
		tput el
	done
	tput cnorm
}

print_options() {
	local _COUNTER=0
	for _OPTION in ${_OPTIONS[@]}; do
		if (( _COUNTER == _CURSOR )); then
			echo " \e[1m\e[32m→\e[0m  \e[1m$_OPTION\e[0m"
		else
			echo "    $_OPTION"
		fi
		((_COUNTER++))
	done
	echo
}

key_press_down() {
	(( _CURSOR < _OPTIONS_LENGTH )) && (( _CURSOR++ ))
	clear_options
	print_options
}

key_press_up() {
	(( _CURSOR > 0 )) && (( _CURSOR-- ))
	clear_options
	print_options
}

check_key_code() {
	if [[ $1 =~ "1b5b 4100" ]]; then
		key_press_up
		catch_key_press
	elif [[ $1 =~ "1b5b 4200" ]]; then
		key_press_down
		catch_key_press
	elif [[ $1 =~ "0d00 0000" ]]; then
		# enter
		echo $_CURSOR > $_RESULT_FILE
	elif [[ $1 =~ "1b00 0000" ]]; then
		# esc
		exit 1
	elif [[ $1 =~ "5100 0000" ]]; then
		# Q
		exit 1
	elif [[ $1 =~ "7100 0000" ]]; then
	 	# q
		exit 1
	fi
}

# Catch key press action and convert to 
catch_key_press() {
	local _KEYCODE
	{
		stty raw isig -echo
		local _KEY=$(dd bs=8 conv=sync count=1)
		_KEYCODE=$(printf %s $_KEY | xxd)
		reset_stty
	} </dev/tty 2>/dev/null
	check_key_code $_KEYCODE
}

print_options
catch_key_press